id = "palenight-dark-theme"
name = "Palenight Dark"
version = "0.3.0"
schema_version = 1
description = "Palenight Dark theme for Zed"
repository = "https://github.com/stackia/zed-palenight-dark"
authors = ["Stackie Jia <jsq2627@gmail.com>"]
